### ISSUE TITLE
Why are timeouts specified in seconds?

### ISSUE THREAD

**Issue by bocytko** [zalando-incubator/put-it-to-rest#27]
Why are read & connect timeouts configured in seconds?

**Comment by lukasniemeier-zalando** [comment]
Having timeouts in seconds might be the wrong spirit, I agree. Switch to `TimeUnit`?

**Comment by whiskeysierra** [comment]
Like this?

```yaml
rest:
  oauth:
    access-token-url: https://auth.example.com
    scheduling-period: 10
    timeouts:
      connect: 1
      connect-unit: seconds
      read: 500
      read-unit: milliseconds
```
