### ISSUE TITLE
Expose generic configuration

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-incubator/put-it-to-rest#51]
The HttpClientBuilder + RequestConfig expose setters for various properties, including but not limited to:
- connectTimeout (in millis)
- socketTimeout (in millis)
- connectionTimeToLive (time + unit)
- maxConnPerRoute
- maxConnTotal

Would be nice if we support those things natively in yaml:

```yaml
rest:
  clients:
    example:
      default-request-config:
        connect-timeout: 10000
        socket-timeout: 10000
      conn-time-to-live: 30
      conn-time-to-live-unit: seconds
      max-conn-per-route: 10
      max-conn-total: 10
```

It's unfortunate that the HttpClient in itself is not consistent with the naming and data types but at least it would remove the need to specify/document everything. We just pass things along *as-is*.
