### ISSUE TITLE
Default settings for max-connections-per-route and max-connections-total are not respected

### ISSUE THREAD

**Issue by i8r** [zalando-incubator/put-it-to-rest#59]
Given the following configuration

```yaml
rest:
  defaults:
    max-connections-per-route: 16
    max-connections-total: 20
  clients:
    someclient:
      baseUrl: http://localhost
```

the global defaults `max-connections-per-route` and `max-connections-total` are not respected for the client `someclient`.

The problem seems to be that [RestSettings](https://github.com/zalando-incubator/put-it-to-rest/blob/master/src/main/java/org/zalando/putittorest/RestSettings.java) is using primitives, but [RestClientPostProcessor](https://github.com/zalando-incubator/put-it-to-rest/blob/master/src/main/java/org/zalando/putittorest/RestClientPostProcessor.java#L285) assumes a `null` value.
